### ISSUE TITLE
Problem when file name (title) gets too long

### ISSUE THREAD

**Issue by thilop** [wooni005/exitwp-for-hugo#6]
I got this:

`IOError: [Errno 36] File name too long`

I guess best solution would be to truncate to OS limits?

Also script should skip not break

**Comment by wooni005** [comment]
Good idea. Do you've a row number where the error is reported?

Op za 1 okt. 2022 om 11:52 schreef Thilo Pfennig ***@***.***>:

**Comment by wooni005** [comment]
And what OS do you use?

Op za 1 okt. 2022 om 12:12 schreef Arjan Wooning ***@***.***>:

**Comment by thilop** [comment]
I use Linux Mint. Here is a snippet. Its not really hidden content, so giving a full quote of the log is ok for me

```
  File "./exitwp.py", line 398, in <module>
    write_jekyll(data, target_format)
  File "./exitwp.py", line 324, in write_jekyll
    out = open_file(fn)
  File "./exitwp.py", line 210, in open_file
    f = codecs.open(file, 'w', encoding='utf-8')
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 36] File name too long: u'build/hugo/kielkontrovers.com/_posts/2011-07-06-ti-podcat-korruptionspravention-auf-kommunaler-ebene-beginnt-mit-einem-klaren-politischen-bekenntnis-ulrike-lohr-bei-transparency-im-gesprach.markdown'

```

**Comment by thilop** [comment]
From the XML file:
`  <wp:post_name>ti-podcat-korruptionspravention-auf-kommunaler-ebene-beginnt-mit-einem-klaren-politischen-bekenntnis-ulrike-lohr-bei-t       ransparency-im-gesprach</wp:post_name>
`

**Comment by wooni005** [comment]
Hi Thilo,
I send you a request to your email for sending the Wordpress export XML file or a part of it. I don't have any export file available here nor Wordpress sites. Hard to test without any input files ;-)

**Comment by wooni005** [comment]
Maybe the most simple solution is to make the url shorter than 255 bytes and export again. An URL longer than 255 bytes is also for search engines not recommended.
I will close this issue

**Comment by thilop** [comment]
> Maybe the most simple solution is to make the url shorter than 255 bytes and export again. An URL longer than 255 bytes is also for search engines not recommended. I will close this issue

Well thats for Wordpress to decide. There is no limit in the length for a title in Wordpress and Wordpress made those titles. As my archive is from 2009 and has a text size of 15 MB this will take some time. I first need to find out how I can manipulate the URL length, maybe in vim or sed?

**Comment by wooni005** [comment]
Yes, converting from WP to Hugo is not a walk in the park. If you've a non
complex website, maybe it's converted in one iteration. But most of the
time it takes a lot of changes and iterations to have a good result.
In Wordpress the url is generated out of the title and is called the slug.
You can see this slug in Wordpress.

Op zo 2 okt. 2022 om 16:51 schreef Thilo Pfennig ***@***.***>:

**Comment by thilop** [comment]
> Yes, converting from WP to Hugo is not a walk in the park. If you've a non complex website, maybe it's converted in one iteration. But most of the time it takes a lot of changes and iterations to have a good result. In Wordpress the url is generated out of the title and is called the slug. You can see this slug in Wordpress. 

Actually I just want to fill the archive with the markdown. I dont need a 1:1 transfer. Also I guess I will reconsider categories and tags-
